### ISSUE TITLE
[stacks-signer] cast_aggregate_public_key vote stx transaction

### ISSUE THREAD

**Issue by jferrant** [stacks-archive/sbtc-developer-release#392]
### Description

Create a helper function that constructs a cast_aggregate_public_key stx transaction given a Point as input

This function will ultimately be calling the clarity function created as part of https://github.com/stacks-network/stacks-core/issues/3968

### Acceptance Criteria

- [ ] PR adds the feature

**Comment by jferrant** [comment]
See https://github.com/Trust-Machines/stacks-sbtc/blob/main/sbtc-mini/contracts/sbtc-stacking-pool.clar
"vote-for-threshold-wallet-candidate" function.

**Comment by friedger** [comment]
The implementation on the clarity side is developed at https://github.com/stacks-network/stacks-core/pull/4116
